### ISSUE TITLE
Test summarize trigger

### ISSUE THREAD

**Issue by adrianoapmartins** [trailblazing-reviewpad/main-trail#15]
Config:
```yaml
  # Runs Reviewpad Summarize on open GitHub Issues
  - name: summarize-issue
    always-run: true
    on:
      - issue
    if: $state() == "open"
    then: $summarize()
```
